spring.application.name=connect-eureka-server
server.port=8761
server.address=0.0.0.0

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false

# IMPORTANT: Do NOT force hostname
eureka.instance.hostname=${spring.cloud.client.hostname}

management.endpoints.web.exposure.include=*
